apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth
    labels:
        app: auth
spec:
    replicas: 2
    selector:
        matchLabels:
            app: auth
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 3
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: devpiush/python-microservice-auth:latest
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - configMapRef:
                            name: auth-config
                      - secretRef:
                            name: auth-secrets
